# From: 
# https://github.com/google/mediapipe/pull/867/commits/19983e3bd924c6547cc7e2728d0623107a135554

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "counting_vector_size_calculator",
    srcs = ["counting_vector_size_calculator.cc"],
    hdrs = ["counting_vector_size_calculator.h"],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "//mediapipe/framework:calculator_framework",
        "//mediapipe/framework/formats:landmark_cc_proto",
    ],
    alwayslink = 1,
)